# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  build: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - task: Docker@2
      displayName: Build the image
      inputs:
        repository: 'renkman/renkbench'
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: --build-arg buildnumber=$(build)
        tags: latest
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'renkman/renkbench'
        command: 'push'
        tags: latest
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'        
      displayName: 'Publish files'