trigger:
  - master
    
resources:
- repo: self

variables:
  buildNumber: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - task: DockerCompose@0
      displayName: Build the images
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'BUILDNUMBER=$(buildNumber)'
        action: 'Build services'    
    - task: DockerCompose@0
      displayName: Run tests
      inputs:
          dockerComposeFile: '**/docker-compose.yml'
          dockerComposeFileArgs: 'BUILDNUMBER=$(buildNumber)'
          action: 'Run a specific service'
          serviceName: test
          detached: false
    - task: DockerCompose@0
      displayName: Push the images
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
    - task: CopyFiles@2
      displayName: Copy docker-compose.yml to $(Build.ArtifactStagingDirectory)
      inputs:
        Contents: |
          **/docker-compose.yml
          **/.env
          **/run_docker_compose.sh          
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'