name: Renkbench CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: API unit tests
      run: |
        cd src
        docker-compose -f docker/docker-compose.yml up test-backend
        docker cp test-backend:/src/api/coverage.out ./

    - name: Frontend unit tests
      run: |
        cd src
        docker-compose -f docker/docker-compose.yml up test-frontend

    - name: Docker cleanup
      run: |
        cd src
        docker-compose -f docker/docker-compose.yml down

    - name: Build the API
      run: |
        cd src
        docker-compose -f docker/docker-compose.yml build app

    - name: Build the db init
      run: |
        cd src
        docker-compose -f docker/docker-compose.yml build init

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push docker images to Docker Hub
      run: |
        docker push renkman/renkbench
        docker push renkman/renkbench-init

    - name: Deploy to renkbench.de
      run |
        echo "${{ secrets.DOCKER_USERNAME }}" > key
        chmod 600 key
        scp -i key src/docker/docker-compose.yml root@178.128.195.176:/root/deploy
        scp -i key src/docker/mongo-init.sh root@178.128.195.176:/root/deploy
        rm key
