name: Renkbench CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the API
      run: |
        cd app
        docker-compose -f docker/docker-compose.yml build app

    - uses: actions/checkout@v3
    - name: API unit tests
      run: |
        cd app
        docker-compose -f docker/docker-compose.yml up test-backend

    - uses: actions/checkout@v3
    - name: Frontend unit tests
      run: |
        cd app
        docker-compose -f docker/docker-compose.yml up test-frontend
